support specifying a favicon folder
withletters/papery pull request #10
Opened 2020-12-18 08:53 UTC by tkatox

support customize assets directory path
#7 

・themes_assets
・files_assets

2020-12-28 02:37 UTC, na4da requested changes
I confirmed that this feature works correctly. Thanks!
And I commented about the config.

2020-12-28 02:37 UTC, na4da commented on papery/rendering.py
> +            self.config['themes_assets'] = "assets"
I recommend to fix config coerced to use underscore. As setting [`self.config`](https://github.com/withletters/papery/blob/master/papery/rendering.py#L44), please add the code like below.

```python
fixed_config = {}
    for k, v in config.items():
        fixed_config[re.sub('-', '_', k)] = v  # import 're' beforehand
self.config = fixed_config
```

2020-12-28 09:12 UTC, na4da approved these changes
LGTM 👍

2021-06-07 11:44 UTC, federkasten approved these changes

2021-06-07 11:45 UTC, merged