Support emoji
withletters/papery pull request #14
Opened 2022-04-15 08:22 UTC by tkatox

・support emoji #13
・python to python3

2022-04-20 05:28 UTC, na4da requested changes
Thank you for working on this! I confirmed that emoji is displayed on sample page by `papery run`.

2022-04-20 05:28 UTC, na4da commented on papery/data/sample/themes/default/assets/css/style.css
> +  height: 1em;
```suggestion
  display: inline-flex;
  height: 1.25em;
  vertical-align: text-top;
```

By applying the emoji style that's actually used on [PyMdown Extensions Documentation](https://facelessuser.github.io/pymdown-extensions/extensions/emoji/), I think it looks better.

2022-04-20 07:06 UTC, na4da approved these changes
LGTM 👍

2022-08-27 05:30 UTC, federkasten approved these changes

2022-08-27 05:30 UTC, federkasten commented on papery/page.py
> +                                             # TODO make "image_path" configurable by papery's configuration file for security reasons
I don't want to load emoji files from a CDN for security reasons especially for internal sites.

2022-08-27 05:30 UTC, merged