support YAML
withletters/papery pull request #4
Opened 2020-10-26 08:21 UTC by tkatox

YAMLファイルも使えるようにしました。

2020-11-06 04:12 UTC, na4da requested changes
It's confirmed that `papery` command installed by `pip install  -e .` works correctly even YAML-based config and index are applied. Thank you!
I commented about the code appearance.

2020-11-06 07:44 UTC, na4da approved these changes
LGTM. Thanks!

2020-11-10 03:14 UTC, federkasten approved these changes
LGTM :+1:  I commented on some minor points.

2020-11-10 03:14 UTC, federkasten commented on papery/data/sample/config.yaml
> +    path: /
Please delete the corresponding JSON.

2020-11-10 03:14 UTC, federkasten commented on README.md
> +papery is  is a simple, static site generator written in Python - supports Markdown/JSON/YAML input and Jinja2 templating.
```suggestion
papery is  is a simple, static site generator written in Python - supports Markdown, YAML, and JSON input and Jinja2 templating.
```

2020-11-10 03:14 UTC, federkasten commented on papery/engine.py
> +                  config_path = 'config.yaml'
```suggestion
                    config_path = 'config.yaml'
```

2020-11-10 03:18 UTC, federkasten approved these changes

2020-11-10 03:18 UTC, federkasten commented on papery/rendering.py
> +              info = page_base + ".json"
```suggestion
            if os.path.exists(page_base + ".yaml"):
                info = page_base + ".yaml"
            else:
                info = page_base + ".json"
```

2020-11-14 04:35 UTC, merged